export const FEATURE_KEYS = {
    MENTOR_SESSIONS_MONTHLY: 'mentor_sessions_monthly',
    SESSION_DURATION_MINUTES: 'session_duration_minutes',
    DIRECT_MESSAGES_DAILY: 'direct_messages_daily',
    MESSAGE_REQUESTS_DAILY: 'message_requests_daily',
    AI_HELPER_CHAT_ACCESS: 'ai_helper_chat_access',
    AI_HELPER_MESSAGES_LIMIT: 'ai_helper_messages_limit',
    AI_CHAT_MAX_USER_MESSAGES: 'ai_chat_max_user_messages',
    FREE_COURSES_LIMIT: 'free_courses_limit',
    SESSION_RECORDINGS_ACCESS: 'session_recordings_access',
    // Mentor & mentee feature gates
    MENTOR_PROFILE_ACCESS: 'mentor_profile_access',
    MENTEE_PROFILE_ACCESS: 'mentee_profile_access',
    COMPANY_PAGE_ACCESS: 'company_page_access',
    AI_VISIBILITY: 'ai_visibility',
    AI_SEARCH_SESSIONS: 'ai_search_sessions',
    AI_SEARCH_SESSIONS_MONTHLY: 'ai_search_sessions_monthly',
    LEAD_QUALIFYING_SESSION_MINUTES: 'lead_qualifying_session_minutes',
    FREE_VIDEO_SESSIONS_MONTHLY: 'free_video_sessions_monthly',
    PAID_VIDEO_SESSIONS_MONTHLY: 'paid_video_sessions_monthly',
    COUNSELING_SESSIONS_MONTHLY: 'counseling_sessions_monthly',
    CONTENT_POSTING_ACCESS: 'create_post_content',
    ROADMAP_UPLOAD_ACCESS: 'roadmap_upload',
    ROADMAP_DOWNLOAD_ACCESS: 'roadmap_download',
    KNOWLEDGE_HUB_ACCESS_LEVEL: 'knowledge_hub_access',
    INDUSTRY_EXPERT_LISTING_LIMIT: 'industry_expert_listing',
    INDUSTRY_EXPERT_ACCESS_LEVEL: 'industry_expert_access',
    LIVE_SESSIONS_MINUTES_MONTHLY: 'live_sessions_minutes_monthly',
    LIVE_SESSIONS_COUNT_MONTHLY: 'live_sessions_count_monthly',
    COURSE_VIDEOS_MONTHLY: 'course_videos_monthly',
    COURSES_ACCESS: 'courses_access',
    COURSE_DISCOUNT_PERCENT: 'course_discount_percent',
    TEAM_MEMBER_LIMIT: 'team_member_limit',
    EXCLUSIVE_PARTNER_OFFERS_ACCESS: 'exclusive_partner_offers_access',
    EARLY_ACCESS_FEATURES: 'early_access_features',
    // Admin/System features
    PLATFORM_FEE_PERCENTAGE: 'platform_fee_percentage',
    MAX_MENTEES_LIMIT: 'max_mentees_limit',
    PROFILE_VERIFICATION_PRIORITY: 'profile_verification_priority',
    FEATURED_MENTOR_LISTING: 'featured_mentor_listing',
    ANALYTICS_ACCESS_LEVEL: 'analytics_dashboard',
    CUSTOM_BRANDING: 'custom_branding',
    PRIORITY_SUPPORT: 'priority_support',
    PRIORITY_MESSAGING: 'priority_messaging',
  } as const;

export type FeatureKey = (typeof FEATURE_KEYS)[keyof typeof FEATURE_KEYS];
