services:
  postgres:
    image: postgres:18
    container_name: sharing-minds-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sharing_minds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - sharing-minds-postgres-data:/var/lib/postgresql
      - .:/dumps:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d sharing_minds']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sharing-minds-pgadmin
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - sharing-minds-pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro

volumes:
  sharing-minds-postgres-data:
  sharing-minds-pgadmin-data:
