// Export all schema files
export * from './users';
export * from './roles';
export * from './user-roles';
export * from './mentors';
export * from './mentees';
export * from './sessions';
export * from './messages';
export * from './message-requests';
export * from './messaging-permissions';
export * from './message-threads';
export * from './message-reactions';
export * from './mentoring-relationships';
export * from './auth';
export * from './mentor-content';
export * from './course-enrollment';
export * from './learning-analytics';
export * from './ai-chatbot-messages';
export * from './ai-chatbot-message-insights';
export * from './notifications';
export * from './contact-submissions';
export * from './consent-events';
export * from './audit-events';
export * from './admin-audit-trail';
export * from './email-events';
export * from './mentor-availability';
export * from './reviews';
export * from './livekit';
export * from './mentee-profile-audit';
export * from './mentors-form-audit-trail';
export * from './mentors-profile-audit';
export * from './session-policies';
export * from './session-audit-log';
export * from './reschedule-requests';
export * from './admin-session-audit-trail';
export * from './admin-session-notes';
export * from './subscriptions';
export * from './payments';
export * from './access-policy-configs';

// Temporary empty export to prevent TypeScript errors
export { };
